create table Person (
    id int generated by default as identity primary key,
    name varchar (100) NOT NULL unique ,
    year int check ( year > 1900 )
    );

INSERT INTO Person(name, year) VALUES ('Michael Good', 1965);
INSERT INTO Person(name, year) VALUES ('David Finch', 2001);
INSERT INTO Person(name, year) VALUES ('Billy Kane', 1989);
INSERT INTO Person(name, year) VALUES ('Lucy Woo', 1996);
INSERT INTO Person(name, year) VALUES ('Angela Baker', 1978);
INSERT INTO Person(name, year) VALUES ('Donald White', 1959);
INSERT INTO Person(name, year) VALUES ('Liam Fox', 2009);

CREATE TABLE Book(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visitor_id int references person(id) on DELETE SET NULL,
    name varchar(100) NOT NULL UNIQUE,
    author varchar(100) not null,
    year int CHECK (year > 0)
    );

INSERT INTO Book(name, author, year) VALUES ('The Great Gatsby', 'F. Scott Fitzgerald', 1925);
INSERT INTO Book(name, author, year) VALUES ('Moby Dick', 'Herman Melville', 1851);
INSERT INTO Book(name, author, year) VALUES ('War and Peace', 'Leo Tolstoy', 1869);
INSERT INTO Book(name, author, year) VALUES ('One Hundred Years of Solitude', 'Gabriel Garcia Marquez', 1967);
INSERT INTO Book(name, author, year) VALUES ('Don Quixote', 'Miguel de Cervantes', 1605);
INSERT INTO Book(name, author, year) VALUES ('Hamlet', 'William Shakespeare', 1599);
INSERT INTO Book(name, author, year) VALUES ('The Divine Comedy', 'Dante Alighieri', 1320);
INSERT INTO Book(name, author, year) VALUES ('Crime and Punishment', 'Fyodor Dostoyevsky', 1866);
INSERT INTO Book(name, author, year) VALUES ('The Adventures of Huckleberry Finn', 'Mark Twain', 1884);
INSERT INTO Book(name, author, year) VALUES ('Alices Adventures in Wonderland', 'Lewis Carroll', 1862);