create table Person (
    id int generated by default as identity primary key,
    full_name varchar (100) NOT NULL unique,
    year_of_birth int NOT NULL check ( Person.year_of_birth > 1900 )
);

INSERT INTO Person(full_name, year_of_birth) VALUES ('Michael Good', 1965);
INSERT INTO Person(full_name, year_of_birth) VALUES ('David Finch', 2001);
INSERT INTO Person(full_name, year_of_birth) VALUES ('Billy Kane', 1989);
INSERT INTO Person(full_name, year_of_birth) VALUES ('Lucy Woo', 1996);
INSERT INTO Person(full_name, year_of_birth) VALUES ('Angela Baker', 1978);
INSERT INTO Person(full_name, year_of_birth) VALUES ('Donald White', 1959);
INSERT INTO Person(full_name, year_of_birth) VALUES ('Liam Fox', 2009);

CREATE TABLE Book(
   id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   title varchar(100) NOT NULL UNIQUE,
   author varchar(100) not null,
   year int not null CHECK (year > 0),
   person_id int references person(id) on DELETE SET NULL
);

INSERT INTO Book(title, author, year) VALUES ('The Great Gatsby', 'F. Scott Fitzgerald', 1925);
INSERT INTO Book(title, author, year) VALUES ('Moby Dick', 'Herman Melville', 1851);
INSERT INTO Book(title, author, year) VALUES ('War and Peace', 'Leo Tolstoy', 1869);
INSERT INTO Book(title, author, year) VALUES ('One Hundred Years of Solitude', 'Gabriel Garcia Marquez', 1967);
INSERT INTO Book(title, author, year) VALUES ('Don Quixote', 'Miguel de Cervantes', 1605);
INSERT INTO Book(title, author, year) VALUES ('Hamlet', 'William Shakespeare', 1599);
INSERT INTO Book(title, author, year) VALUES ('The Divine Comedy', 'Dante Alighieri', 1320);
INSERT INTO Book(title, author, year) VALUES ('Crime and Punishment', 'Fyodor Dostoyevsky', 1866);
INSERT INTO Book(title, author, year) VALUES ('The Adventures of Huckleberry Finn', 'Mark Twain', 1884);
INSERT INTO Book(title, author, year) VALUES ('Alices Adventures in Wonderland', 'Lewis Carroll', 1862);